project:
  type: book
  output-dir: docs

book:
  title: "Topological Phases of Matter"
  author: "Emmanuel Calderón"
  date: "9/2/2024"
  chapters:
    - index.qmd
    - 1D_Systems.qmd
    - Hexagonal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    fontsize: 1.0em
    css: styles.css
    code-fold: true
    code-summary: "Code"
    code-line-numbers: true
    code-copy: true
  pdf:
    documentclass: scrreprt

