project:
  type: book
  output-dir: docs

book:
  title: "Topological_Superconductors"
  author: "Emmanuel Calderón"
  date: "9/2/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - SSH.qmd
    - Kitaev_Chain.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    fontsize: 1.0em
    css: styles.css
    code-fold: true
    code-summary: "Code"
    code-line-numbers: true
    code-copy: true
  pdf:
    documentclass: scrreprt



